# Generated by Django 4.1 on 2023-05-01 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iiko', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('num', models.CharField(max_length=16)),
                ('type', models.IntegerField()),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iiko.storage')),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('photo', models.IntegerField(default=0)),
                ('fio', models.CharField(max_length=64)),
                ('birth_date', models.DateField(null=True)),
                ('address', models.CharField(max_length=64, null=True)),
                ('phone', models.CharField(max_length=11)),
                ('is_deleted', models.PositiveSmallIntegerField(default=0)),
                ('dismiss_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('oklad', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=128)),
                ('page', models.CharField(max_length=128)),
                ('action', models.CharField(max_length=32)),
                ('comment', models.CharField(max_length=128, null=True)),
                ('is_bar', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=64)),
                ('text', models.CharField(max_length=64)),
                ('app_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('inn', models.CharField(max_length=12)),
                ('friendly_name', models.CharField(max_length=64)),
                ('expense_type', models.ManyToManyField(to='lk.catalog')),
                ('storage', models.ManyToManyField(to='iiko.storage')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('name', models.CharField(max_length=32)),
                ('is_ended', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('is_correct', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('correct_answers', models.IntegerField()),
                ('logs', models.JSONField()),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lk.employee')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lk.test')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(to='lk.testquestion'),
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=32)),
                ('document_number', models.IntegerField()),
                ('date', models.DateField(null=True)),
                ('date_write_off', models.DateField(null=True)),
                ('date_receipt', models.DateField(null=True)),
                ('sum', models.FloatField()),
                ('payment_purpose', models.CharField(max_length=256)),
                ('comment', models.CharField(max_length=64, null=True)),
                ('linked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lk.card')),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payer', to='lk.partner')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient', to='lk.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('can_all', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_view', models.ManyToManyField(to='lk.navbar')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=32, null=True)),
                ('roles', models.ManyToManyField(to='lk.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('args', models.JSONField(null=True)),
                ('priority_id', models.IntegerField()),
                ('linked_jobs', models.ManyToManyField(to='lk.jobplace')),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('date_at', models.DateField()),
                ('sum', models.IntegerField()),
                ('is_received', models.PositiveSmallIntegerField(default=0)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lk.employee')),
                ('reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lk.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=32)),
                ('date_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('payment_receiver', models.CharField(max_length=64, null=True)),
                ('sum', models.FloatField()),
                ('comment', models.CharField(max_length=128)),
                ('expense_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source', to='lk.catalog')),
                ('expense_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type', to='lk.catalog')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iiko.storage')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='job_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lk.jobplace'),
        ),
        migrations.AddField(
            model_name='employee',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iiko.storage'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='catalog_types',
            field=models.ManyToManyField(to='lk.catalogtype'),
        ),
    ]
