# Generated by Django 4.1 on 2023-05-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0003_remove_profile_roles_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobplace',
            name='oklad',
        ),
        migrations.AddField(
            model_name='jobplace',
            name='gain_shift_oklad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobplace',
            name='main_shift_oklad',
            field=models.IntegerField(default=0),
        ),
    ]
