# Generated by Django 4.1 on 2023-05-23 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0017_storage_terminal_ids'),
        ('lk', '0005_alter_employee_status_itemdeficit'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdeficit',
            name='storage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='iiko.storage'),
            preserve_default=False,
        ),
    ]
