# Generated by Django 4.1 on 2023-05-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0006_itemdeficit_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdeficit',
            name='receive_date',
            field=models.DateTimeField(null=True),
        ),
    ]
