# Generated by Django 4.1 on 2023-05-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0007_itemdeficit_receive_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdeficit',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
