# Generated by Django 4.1 on 2023-05-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0014_alter_employee_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
    ]
