# Generated by Django 4.1 on 2023-05-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0015_remove_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, upload_to='employee_photo'),
        ),
    ]
