# Generated by Django 4.1 on 2023-05-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0016_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(null=True, upload_to='employee_photo'),
        ),
    ]
