# Generated by Django 4.1 on 2023-05-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0017_alter_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='args',
            field=models.JSONField(default=dict),
        ),
    ]
