# Generated by Django 4.1 on 2023-05-31 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0018_catalog_args'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='expense_type',
            new_name='expense_types',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='storage',
            new_name='storages',
        ),
    ]
