# Generated by Django 4.1 on 2023-06-04 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0017_storage_terminal_ids'),
        ('lk', '0019_rename_expense_type_partner_expense_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('review_date', models.DateField()),
                ('review_photo', models.ImageField(upload_to='reviews_photo')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iiko.storage')),
                ('types', models.ManyToManyField(to='lk.jobplace')),
            ],
        ),
    ]
