# Generated by Django 4.1 on 2023-06-04 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0020_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='types',
            new_name='jobs',
        ),
    ]
