# Generated by Django 4.1 on 2023-06-04 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0021_rename_types_review_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_photo',
            new_name='photo',
        ),
    ]
