# Generated by Django 4.1 on 2023-06-06 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0024_employee_reviews_alter_review_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='is_bar',
        ),
    ]
