# Generated by Django 4.1 on 2023-06-06 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0025_remove_logs_is_bar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logs',
            new_name='Log',
        ),
    ]
