# Generated by Django 4.1 on 2023-06-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0027_alter_log_comment_alter_log_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='log',
            name='page',
        ),
        migrations.RemoveField(
            model_name='log',
            name='username',
        ),
        migrations.AddField(
            model_name='log',
            name='additional_data',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='entity',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='owner',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='row',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.PositiveIntegerField(choices=[(1, 'Создание записи'), (2, 'Редактирование записи'), (3, 'Удаление записи'), (4, 'Обновление записи'), (5, 'Копирование записи')]),
        ),
    ]
