# Generated by Django 4.1 on 2023-06-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0028_remove_log_comment_remove_log_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdeficit',
            name='arrived_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='itemdeficit',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
