# Generated by Django 4.1 on 2023-06-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0029_itemdeficit_arrived_amount_itemdeficit_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdeficit',
            name='sended_amount',
            field=models.IntegerField(null=True),
        ),
    ]
