# Generated by Django 4.1 on 2023-06-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0031_alter_itemdeficit_arrived_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobplace',
            old_name='gain_shift_oklad',
            new_name='gain_shift_oklad_accrual',
        ),
        migrations.RenameField(
            model_name='jobplace',
            old_name='main_shift_oklad',
            new_name='gain_shift_oklad_receiving',
        ),
        migrations.AddField(
            model_name='jobplace',
            name='main_shift_oklad_accrual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobplace',
            name='main_shift_oklad_receiving',
            field=models.IntegerField(default=0),
        ),
    ]
