# Generated by Django 4.1 on 2023-06-29 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0035_productremain'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_at', models.DateField()),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Увольнение'), (2, 'Восстановление'), (3, 'Смена статуса'), (4, 'Описание')])),
                ('comment', models.CharField(max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lk.employee')),
            ],
        ),
    ]
