# Generated by Django 4.1 on 2023-06-29 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0036_employeelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dismiss_comment',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status_change_comment',
        ),
    ]
