# Generated by Django 4.1 on 2023-07-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0038_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='faq',
            name='tags',
            field=models.ManyToManyField(to='lk.faqtag'),
        ),
    ]
