services:
  app:
    build:
      context: .
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    env_file:
      - ./app/.env
    command: >
      sh -c "python manage.py migrate
             gunicorn --bind 0.0.0.0:80 config.wsgi -w 20 --timeout 120"

  nginx:
    image: nginx:1.19.8-alpine
    restart: on-failure
    depends_on:
      - app
    ports:
      - "8080:8080"
    env_file:
      - ./app/.env

  redis:
    image: redis:7.0.5-alpine
    restart: always
    hostname: redis

  worker:
    build:
      context: .
    restart: always
    hostname: worker
    entrypoint: celery
    command: -A config.celery.app worker --loglevel=info
    volumes:
      - ./app:/app
    links:
      - redis
    depends_on:
      - redis

  beat_worker:
    build:
      context: .
    restart: always
    hostname: beat_worker
    entrypoint: celery
    command: -A config.celery.app beat -s /tmp/celerybeat-schedule --loglevel=info
    volumes:
      - ./app:/app
    links:
      - redis
    depends_on:
      - redis