services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - ./app/.env
    command: >
      sh -c "python manage.py migrate
             gunicorn --bind 0.0.0.0:8000 config.wsgi"
    depends_on:
      - database

  database:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./app/.env
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A config.celery.app worker --loglevel=info
    volumes:
      - ./app:/app
    links:
      - redis
    depends_on:
      - redis

  beat_worker:
    build:
      context: .
    hostname: beat_worker
    entrypoint: celery
    command: -A config.celery.app beat --loglevel=info
    volumes:
      - ./app:/app
    links:
      - redis
    depends_on:
      - redis

volumes:
  postgres_data: