# Generated by Django 4.1 on 2023-05-01 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('args', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=8, null=True)),
                ('name', models.CharField(max_length=64)),
                ('is_active', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=64)),
                ('parent_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('num', models.CharField(max_length=8)),
                ('code', models.CharField(max_length=8)),
                ('type', models.CharField(max_length=8)),
                ('main_unit', models.CharField(max_length=8)),
                ('minimal', models.IntegerField(null=True)),
                ('for_order', models.IntegerField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iiko.category')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, null=True)),
                ('storage_id', models.CharField(max_length=64, null=True)),
                ('point_of_sale', models.CharField(max_length=64, null=True)),
                ('name', models.CharField(max_length=32)),
                ('entity', models.CharField(max_length=32)),
                ('district', models.CharField(max_length=8)),
                ('is_hide', models.PositiveSmallIntegerField()),
                ('is_office', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=64)),
                ('deleted', models.BooleanField()),
                ('friendly_name', models.CharField(max_length=32, null=True)),
                ('is_revise', models.PositiveSmallIntegerField(null=True)),
                ('category', models.ManyToManyField(to='iiko.category')),
            ],
        ),
        migrations.CreateModel(
            name='StopList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_at', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iiko.product')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iiko.storage')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iiko.supplier'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_at', models.DateField()),
                ('order_num', models.IntegerField()),
                ('discount_percent', models.IntegerField()),
                ('order_sum', models.IntegerField()),
                ('order_sum_after_discount', models.IntegerField()),
                ('discount_type', models.CharField(max_length=32)),
                ('discount_owner', models.CharField(max_length=32)),
                ('is_deleted', models.PositiveSmallIntegerField()),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iiko.storage')),
            ],
        ),
    ]
