# Generated by Django 4.1 on 2023-05-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='code',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='entity',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
