# Generated by Django 4.1 on 2023-05-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0002_alter_storage_code_alter_storage_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoplist',
            name='date_at',
            field=models.DateTimeField(),
        ),
    ]
