# Generated by Django 4.1 on 2023-05-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0004_alter_product_name_alter_product_parent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_unit',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='num',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(max_length=16),
        ),
    ]
