# Generated by Django 4.1 on 2023-05-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0007_alter_product_code_alter_product_main_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='args',
        ),
        migrations.AddField(
            model_name='category',
            name='is_income',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='is_remains',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='is_sales',
            field=models.BooleanField(default=False),
        ),
    ]
