# Generated by Django 4.1 on 2023-05-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0008_remove_category_args_category_is_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_income',
            field=models.BooleanField(choices=[(0, 'Не привязано'), (1, 'Привязано')], default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_remains',
            field=models.BooleanField(choices=[(0, 'Не привязано'), (1, 'Привязано')], default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_sales',
            field=models.BooleanField(choices=[(0, 'Не привязано'), (1, 'Привязано')], default=False),
        ),
    ]
