# Generated by Django 4.1 on 2023-05-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0009_alter_category_is_income_alter_category_is_remains_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='is_active',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Активирован'), (1, 'Не активирован')]),
        ),
    ]
