# Generated by Django 4.1 on 2023-05-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0010_alter_paymenttype_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='is_active',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Активен'), (1, 'Не активен')]),
        ),
    ]
