# Generated by Django 4.1 on 2023-05-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0012_alter_paymenttype_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='is_active',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Неактивен'), (1, 'Активен')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_revise',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Сверен'), (1, 'Не сверен')], default=0, null=True),
        ),
    ]
