# Generated by Django 4.1 on 2023-05-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0014_alter_supplier_is_revise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='is_revise',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Сверен'), (0, 'Не сверен')], default=0),
        ),
    ]
