# Generated by Django 4.1 on 2023-06-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0017_storage_terminal_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.CharField(max_length=255)),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('total_day', models.IntegerField(null=True)),
                ('sum_for_percent', models.IntegerField(null=True)),
                ('total_cash', models.IntegerField(null=True)),
                ('total_bn', models.IntegerField(null=True)),
                ('cash', models.IntegerField(null=True)),
                ('cash_point', models.IntegerField(null=True)),
                ('yandex', models.IntegerField(null=True)),
                ('delivery', models.IntegerField(null=True)),
                ('sum_cash_morning', models.IntegerField()),
                ('sum_cash_end_day', models.IntegerField()),
                ('calculated', models.IntegerField(null=True)),
                ('difference', models.IntegerField(null=True)),
                ('expenses_nal', models.IntegerField(null=True)),
                ('salary_prepayment', models.IntegerField(null=True)),
                ('salary_month', models.IntegerField(null=True)),
                ('payin', models.IntegerField(null=True)),
                ('payout', models.IntegerField(null=True)),
            ],
        ),
    ]
