# Generated by Django 4.1 on 2023-05-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0018_storage_terminal_ids_delete_terminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='terminal_ids',
            field=models.JSONField(default=list, null=True),
        ),
    ]
