# Generated by Django 4.1 on 2023-06-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0021_alter_session_close_date_alter_session_open_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='sum_cash_end_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='sum_cash_morning',
            field=models.IntegerField(null=True),
        ),
    ]
