# Generated by Django 4.1 on 2023-06-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0022_alter_session_sum_cash_end_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date_at',
            field=models.DateField(null=True),
        ),
    ]
