# Generated by Django 4.1 on 2023-06-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0025_alter_session_close_date_alter_session_open_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='calculated',
        ),
        migrations.RemoveField(
            model_name='session',
            name='difference',
        ),
        migrations.RemoveField(
            model_name='session',
            name='expenses_nal',
        ),
        migrations.RemoveField(
            model_name='session',
            name='payin',
        ),
        migrations.RemoveField(
            model_name='session',
            name='payout',
        ),
        migrations.RemoveField(
            model_name='session',
            name='salary_month',
        ),
        migrations.RemoveField(
            model_name='session',
            name='salary_prepayment',
        ),
        migrations.RemoveField(
            model_name='session',
            name='sum_cash_end_day',
        ),
        migrations.RemoveField(
            model_name='session',
            name='sum_cash_morning',
        ),
        migrations.RemoveField(
            model_name='session',
            name='sum_for_percent',
        ),
        migrations.RemoveField(
            model_name='session',
            name='total_bn',
        ),
        migrations.RemoveField(
            model_name='session',
            name='total_cash',
        ),
        migrations.RemoveField(
            model_name='session',
            name='total_day',
        ),
    ]
