# Generated by Django 4.1 on 2023-06-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0026_remove_session_calculated_remove_session_difference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
