# Generated by Django 4.1 on 2023-06-24 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0028_remove_storage_terminal_ids_terminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='discount',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iiko.discounttype'),
        ),
    ]
