# Generated by Django 4.1 on 2023-06-28 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0029_discounttype_alter_discount_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRemain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iiko.product')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iiko.storage')),
            ],
        ),
    ]
