# Generated by Django 4.1 on 2023-06-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0030_productremain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductRemain',
        ),
    ]
