# Generated by Django 4.1 on 2023-05-01 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lk', '0001_initial'),
        ('iiko', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TovarRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('product_amount', models.IntegerField()),
                ('product_main_unit', models.CharField(max_length=32)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iiko.product')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iiko.storage')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iiko.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('oklad', models.IntegerField()),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lk.employee')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lk.position')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iiko.storage')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField(null=True)),
                ('expenses_types_with_employees_in_comment', models.ManyToManyField(to='lk.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Аванс'), (2, 'Расчет')])),
                ('oklad', models.IntegerField()),
                ('percent', models.IntegerField(default=0)),
                ('premium', models.IntegerField(default=0)),
                ('month', models.IntegerField(null=True)),
                ('period', models.IntegerField(null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lk.employee')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iiko.storage')),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Внесение'), (2, 'Изъятие'), (4, 'Закупщик')])),
                ('sum', models.FloatField()),
                ('comment', models.CharField(max_length=64)),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iiko.storage')),
            ],
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('date_at', models.DateField()),
                ('sum_cash_morning', models.IntegerField()),
                ('total_cash', models.IntegerField(null=True)),
                ('total_bn', models.IntegerField(null=True)),
                ('total_day', models.IntegerField(null=True)),
                ('total_market', models.IntegerField(null=True)),
                ('total_expenses', models.IntegerField(null=True)),
                ('total_salary', models.IntegerField(null=True)),
                ('total_payin', models.IntegerField(null=True)),
                ('total_payout', models.IntegerField(null=True)),
                ('deposit', models.IntegerField(null=True)),
                ('sum_cash_end_day', models.IntegerField(null=True)),
                ('calculated', models.IntegerField(null=True)),
                ('difference', models.IntegerField(null=True)),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iiko.storage')),
            ],
        ),
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_at', models.DateField()),
                ('num', models.CharField(max_length=64)),
                ('amount', models.IntegerField()),
                ('sum', models.FloatField()),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Неоплачено'), (1, 'Оплачено'), (2, 'Оплачено БАР')], default=0)),
                ('payment_date', models.DateField(null=True)),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lk.catalog')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iiko.product')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iiko.storage')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iiko.supplier')),
            ],
        ),
    ]
