# Generated by Django 4.1 on 2023-05-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0006_alter_pays_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pays',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Внесение'), (2, 'Изъятие'), (4, 'Закупщик'), (5, 'Масло'), (6, 'Данил')]),
        ),
    ]
