# Generated by Django 4.1 on 2023-05-22 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0004_remove_jobplace_oklad_jobplace_gain_shift_oklad_and_more'),
        ('bar', '0007_alter_pays_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='fine_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lk.catalog'),
        ),
    ]
