# Generated by Django 4.1 on 2023-05-24 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0017_storage_terminal_ids'),
        ('bar', '0009_remove_timetable_fine_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='args',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='setting',
            name='storage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='iiko.storage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='tg_chat_id',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
