# Generated by Django 4.1 on 2023-05-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0010_setting_args_setting_storage_setting_tg_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='tg_chat_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
