# Generated by Django 4.1 on 2023-05-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0011_alter_setting_tg_chat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='args',
            new_name='bar_info',
        ),
    ]
