# Generated by Django 4.1 on 2023-06-04 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0026_remove_session_calculated_remove_session_difference_and_more'),
        ('bar', '0012_rename_args_setting_bar_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iiko.session'),
        ),
    ]
