# Generated by Django 4.1 on 2023-05-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0012_rename_args_setting_bar_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='barmen_percent',
            field=models.FloatField(null=True),
        ),
    ]
