# Generated by Django 4.1 on 2023-05-30 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0018_catalog_args'),
        ('bar', '0013_money_barmen_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pays',
            name='from_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lk.catalog'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Внесение'), (2, 'Изъятие')]),
        ),
    ]
