# Generated by Django 4.1 on 2023-06-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0014_pays_from_to_alter_pays_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndDayQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='setting',
            name='end_day_questions',
            field=models.ManyToManyField(to='bar.enddayquestions'),
        ),
    ]
