# Generated by Django 4.1 on 2023-06-08 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0013_money_session'),
        ('bar', '0015_enddayquestions_setting_end_day_questions'),
    ]

    operations = [
    ]
