#  Copyright (c) 2023. All rights reserved. Mikhail Luginin. Contact: telegram @hex0z

# Generated by Django 4.1 on 2023-07-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bar', '0016_merge_20230609_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalKeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_invoice_num', models.CharField(max_length=255)),
                ('gave_thirty', models.PositiveIntegerField()),
                ('received_thirty', models.PositiveIntegerField()),
                ('gave_fifty', models.PositiveIntegerField()),
                ('received_fifty', models.PositiveIntegerField()),
            ],
        ),
    ]
