

# Generated by Django 4.1 on 2023-07-01 21:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bar', '0017_arrivalkeg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrivalkeg',
            old_name='arrival_invoice_num',
            new_name='invoice_number',
        ),
    ]
