# Generated by Django 4.1 on 2023-07-10 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iiko', '0031_delete_productremain'),
        ('lk', '0037_remove_employee_description_and_more'),
        ('bar', '0018_rename_arrival_invoice_num_arrivalkeg_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_at', models.DateField()),
                ('number', models.CharField(max_length=255)),
                ('sum', models.IntegerField()),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Неоплачено'), (1, 'Оплачено'), (2, 'Оплачено БАР')], default=0)),
                ('payment_date', models.DateField(null=True)),
                ('arrivals', models.ManyToManyField(to='bar.arrival')),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lk.catalog')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iiko.storage')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iiko.supplier')),
            ],
        ),
    ]
