# Generated by Django 4.1 on 2023-07-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0019_arrivalinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivalinvoice',
            name='sum',
            field=models.FloatField(),
        ),
    ]
