# Generated by Django 4.1 on 2023-07-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0020_alter_arrivalinvoice_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrival',
            name='date_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='arrival',
            name='num',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
